securityTokenService:
  discoveryUrl: ${SECURITY_TOKEN_SERVICE_OPENID_CONFIGURATION_URL}

kafka:
  security.protocol: SSL
  krav.initialisering:
    topic: ${KRAV_INITIALISERING_TOPIC}
    groupid: eessi-pensjon-krav-initialisering-group

eessi.pensjon.krav:
  s3:
    bucket.name: 'eessipensjon-krav'
s3_region: us-east-1

#Metrics
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  endpoint:
    info:
      show-details: "ALWAYS"