
spring:
  kafka:
    listener:
      ack-mode: manual
    consumer:
      enable-auto-commit: false
      max-poll-records: 1
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS_URL}
    properties:
      security.protocol: SASL_SSL
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      sasl:
        mechanism: PLAIN
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${srvusername}" password="${srvpassword}";

securityTokenService:
  discoveryUrl: ${SECURITY_TOKEN_SERVICE_OPENID_CONFIGURATION_URL}

kafka:
  krav.initialisering:
    topic: ${KRAV_INITIALISERING_TOPIC}
    groupid: eessi-pensjon-krav-initialisering-group

s3_region: us-east-1

#Metrics
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  endpoint:
    info:
      show-details: "ALWAYS"