no.nav.security.jwt:
  client:
    registration:
      pensjon-credentials:
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://${AZURE_APP_PEN_CLIENT_ID}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt


kafka:
  security.protocol: SSL
  krav.initialisering:
    topic: ${KRAV_INITIALISERING_TOPIC}
    groupid: eessi-pensjon-krav-initialisering-group

METRICS_REQUESTFILTER_ENABLE: true

#Metrics
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  endpoint:
    info:
      show-details: "ALWAYS"