kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-krav-initialisering-q1
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  kafka:
    pool: nav-dev
  gcp:
    buckets:
      - name: eessi-pensjon-kravinit-dev-q1
        retentionPeriodDays: 30
        lifecycleCondition:
          age: 7
          createdBefore: 2020-01-01
          numNewerVersions: 2
          withState: ANY
        uniformBucketLevelAccess: true
  envFrom:
    - secret: krav-initialisering # value is the secret name in Google Secret Manager
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system

  webproxy: true
  env:
    - name: GCP_BUCKET_NAME
      value: eessi-pensjon-kravinit-dev-q1
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: KRAV_INITIALISERING_TOPIC
      value: eessipensjon.privat-krav-initialisering-q1
    - name: ENV
      value: q1

  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-krav-initialisering-q1.intern.dev.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi