kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-krav-initialisering-q2
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  kafka:
    pool: nav-dev
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: ONPREM_KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: KRAV_INITIALISERING_TOPIC
      value: privat-eessipensjon-krav-initialisering-q2
    - name: SECURITY_TOKEN_SERVICE_OPENID_CONFIGURATION_URL
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q2.preprod.local/SecurityTokenServiceProvider/
    - name: S3_FSS_URL
      value: http://objectstore.rook-ceph.svc.nais.local
    - name: EESSI_PENSJON_KRAV_S3_CREDS_USERNAME
      value: H1IXJNC11DU9UEFSI1VB
    - name: ENV
      value: q2
    - name: BEHANDLEHENDELSE_URL
      value: https://pensjon-pen-q2.nais.preprod.local/pen/api/behandlehendelse/utland/v1/

  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-krav-initialisering-q2.nais.preprod.local
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "4"
      memory: 8096Mi
    requests:
      cpu: 400m
      memory: 4024Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{serviceuserkv}}
        mountPath: /var/run/secrets/nais.io/srveessipensjonkrav
      - kvPath: {{appsecrets}}
        mountPath: /var/run/secrets/nais.io/appcredentials