kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-krav-initialisering-q2
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  kafka:
    pool: nav-dev
  gcp:
    buckets:
      - name: eessi-pensjon-kravinit-dev-q2
        retentionPeriodDays: 30
        lifecycleCondition:
          age: 7
          createdBefore: 2020-01-01
          numNewerVersions: 2
          withState: ANY
        uniformBucketLevelAccess: true
  secureLogs:
    enabled: true
  envFrom:
    - secret: krav-initialisering # value is the secret name in Google Secret Manager
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: eessi-pensjon-onprem-proxy-q2.dev-fss-pub.nais.io

  webproxy: true
  env:
    - name: GCP_BUCKET_NAME
      value: eessi-pensjon-kravinit-dev-q2
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: KRAV_INITIALISERING_TOPIC
      value: eessipensjon.privat-krav-initialisering-q2
    - name: PEN_BEHANDLEHENDELSE_URL
      value: https://eessi-pensjon-onprem-proxy-q2.dev-fss-pub.nais.io/pen/api/behandlehendelse/utland/v1/
    - name: EESSI_PEN_ONPREM_PROXY_URL
      value: https://eessi-pensjon-onprem-proxy-q2.dev-fss-pub.nais.io
    - name: AZURE_APP_PROXY_CLIENT_ID
      value: dev-fss.eessipensjon.eessi-pensjon-onprem-proxy-q2
    - name: ENV
      value: q2

  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-krav-initialisering-q2.intern.dev.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 4000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi