kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-krav-initialisering-q1
  namespace: eessipensjon
  labels:
    team: eessipensjon

spec:
  gcp:
    buckets:
      - name: eessi-pensjon-kravinit-dev-q1
        retentionPeriodDays: 30
        lifecycleCondition:
          age: 7
          createdBefore: 2020-01-01
          numNewerVersions: 2
          withState: ANY
        uniformBucketLevelAccess: true
    permissions:
      - resource:
          apiVersion: storagebuckets.storage.cnrm.cloud.google.com
          kind: Project
          name: eessipensjon
        role: roles/storage.objectAdmin
  envFrom:
    - secret: statistikk # value is the secret name in Google Secret Manager
  azure:
    application:
      enabled: true
    accessPolicy:
      outbound:
        external:
          - host: https://eessi-pensjon-krav-initialisering-q1.dev.intern.nav.no
  webproxy: true
  kafka:
    pool: nav-dev
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: ONPREM_KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: KRAV_INITIALISERING_TOPIC
      value: eessipensjon.privat-krav-initialisering-q1
    - name: S3_FSS_URL
      value: http://objectstore.rook-ceph.svc.nais.local
    - name: EESSI_PENSJON_KRAV_S3_CREDS_USERNAME
      value: H1IXJNC11DU9UEFSI1VB
    - name: ENV
      value: q1
    - name: PEN_BEHANDLEHENDELSE_URL
      value: https://pensjon-pen-q1.nais.preprod.local/pen/api/behandlehendelse/utland/v1/

  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-krav-initialisering-q1.dev.intern.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "4"
      memory: 8096Mi
    requests:
      cpu: 400m
      memory: 4024Mi
