kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-krav-initialisering
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  kafka:
    pool: nav-prod
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: NAMESPACE
      value: p
    - name: ONPREM_KAFKA_BOOTSTRAP_SERVERS_URL
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443
    - name: KRAV_INITIALISERING_TOPIC
      value: eessipensjon.privat-krav-initialisering
    - name: S3_FSS_URL
      value:
    - name: EESSI_PENSJON_KRAV_S3_CREDS_USERNAME
      value: B4FVJDTJNT7S07IJ2ELC
    - name: ENV
      value: prod
    - name: PEN_BEHANDLEHENDELSE_URL
      value: https://pensjon-pen.nais.adeo.no/pen/api/behandlehendelse/utland/v1/

  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-krav-initialisering.nais.adeo.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "4"
      memory: 8096Mi
    requests:
      cpu: 400m
      memory: 4024Mi
