kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-krav-initialisering
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  kafka:
    pool: nav-prod
  gcp:
    buckets:
      - name: eessi-pensjon-krav-init-prod
        retentionPeriodDays: 30
        lifecycleCondition:
          age: 7
          createdBefore: 2020-01-01
          numNewerVersions: 2
          withState: ANY
        uniformBucketLevelAccess: true
  secureLogs:
    enabled: true

  envFrom:
    - secret: krav-initialisering-prod # value is the secret name in Google Secret Manager
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: pensjon-pen.prod-fss-pub.nais.io
  webproxy: true
  env:
    - name: GCP_BUCKET_NAME
      value: eessi-pensjon-krav-init-prod

    - name: SPRING_PROFILES_ACTIVE
      value: prod

    - name: PEN_BEHANDLEHENDELSE_URL
      value: https://pensjon-pen.prod-fss-pub.nais.io/pen/api/behandlehendelse/utland/v1/

    - name: KRAV_INITIALISERING_TOPIC
      value: eessipensjon.privat-krav-initialisering

    - name: AZURE_APP_PEN_CLIENT_ID
      value: prod-fss.pensjondeployer.pensjon-pen

    - name: ENV
      value: p

  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-krav-initialisering.intern.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 500Mi