name: Deploy topics

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'src/**'
jobs:
  deploy_topics:
    name: 'Deploy topics'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v3

      - name: 'Deploy privat-krav-initialisering-q2 to eessipensjon namespace'
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/topics/topic-privat-krav-initialisering-q2.yaml

      - name: 'Deploy privat-krav-initialisering to eessipensjon namespace'
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/topics/topic-privat-krav-initialisering.yaml
